### PR TITLE
Reccomendations

### LINKED ISSUE #181: Bug — recommendation box from autocomplete only works with course title
**Describe the bug**
The recommendation box and autocomplete should work with multiple properties e.g. course level, department, description, etc.

**To Reproduce**

1. Go to course scheduler page
2. Type CSCI into search bar

**Expected behavior**
Recommendation box should show CSCI courses

**Screenshots**

N/A

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 84

**Additional context**

### PR DESCRIPTION
**Pull request by aidan-lane**
**Issue**
> closes #181 

**Database Changes/Migrations**
> None

**Test Modifications**
> None

**Test Procedure**
> N/A

**Photos**
> N/A

**Additional Info**
>Switched to Bootstrap-Vue's debounce function for better readability. Also switched from 350ms to 300ms, feel free to play around with this number. I also removed the recommendation box as discussed during the meeting today. 

>On the backend, I switched the text search operator from & to |. This allows for more "closer matches" to be found. (for example, before this change, searches like "computer of foundations science" would not show "foundations of computer science". Searches like this should now work.

### CODE REVIEW

**Comment by 123joshuawu** [comment]
Resolves issue 2 of #129

File: src/web/src/components/CourseList.vue [hunk 1]
```diff
@@ -5,15 +5,11 @@
         <b-form-input
           id="search"
           v-model="textSearch"
+          :debounce="debounceTime"
```
Comment (123joshuawu) [inline src/web/src/components/CourseList.vue:8]: Cool didn't know about this

**Comment by 123joshuawu** [comment]
This is really cool!!!!
