### PR TITLE
Fixed Reload Issue for Subject Page

### LINKED ISSUE #248: UX Bug — Subject page failed to reload
**Describe the bug**
In any subject page, the page will be displayed after reloading/refresh. "Loading courses..." symbol runs forever.
**To Reproduce**
1. Click on 'Explorer'
2. Click on 'ARTS'
3. Reload the page on the web browser (clicks refresh button)
4. Subject page cannot be initialized

**Expected behavior**
The subject page displays normally after a refresh, just like access "ARTS" through "Explorer" page
**Screenshots**
e4fee292c4c2633e55f2ca5adcfc645

### PR DESCRIPTION
**Pull request by YuetingLiao**
**Issue**

In any subject page, the page reloads forever when refreshing.

*Example:*
> closes #248 

**Database Changes/Migrations**

N/A

*Example:*
> Added table `account_semester_selection` for a mapping from a students account and semester to a class and section (aka class/section selections)

**Test Modifications**

N/A

**Test Procedure**

Show procedure to test functionality with a clear procedure

*Example:*
> 1. Navigate to Explore page
> 2. Clicks "ARTS" button
> 3. Refresh the page
> 4. The subject page is no longer loading forever

**Additional Info**

Ike had the same issue for course explorer page and I used the same code to resolve this problem.
It happens when variable `selectedSemester` is null after refresh page, so calling `getDefaultSemester()` from `AdminService.js` is needed.

### CODE REVIEW

File: src/web/src/pages/SubjectExplorer.vue [hunk 1]
```diff
@@ -105,6 +106,11 @@ export default {
    * subjectCourseArr is an array of course objects
    */
   async created() {
+    const querySemester = this.$route.query.semester;
+    this.selectedSemester =
+      querySemester && querySemester != "null"
+        ? querySemester
+        : await getDefaultSemester();
     getCourses(this.selectedSemester).then((courses) => {
```
Comment (123joshuawu) [inline src/web/src/pages/SubjectExplorer.vue:114]: would prefer this to use await syntax as well

`const courses = await getCourses(this.selectedSemester);`

**Review by 123joshuawu — APPROVED** [review]

**Review by 123joshuawu — APPROVED** [review]

**Review by marchdan — APPROVED** [review]
Looks good! Yay
