### PR TITLE
Mobile UI fixes

### LINKED ISSUE #338: Bug — Course explorer clipping on smaller screen size
**Describe the bug**
The left-hand column of the department-specific course display on the course explorer is clipped on reduced-sized windows on computers and on phone browser screens

**To Reproduce**
1. Navigate to YACS on mobile or computer with a half-width window
2. Navigate to the ARTS courses in the course explorer
3. Try and view the left-hand column of courses

**Expected behavior**
All course objects should be viewable, or page should be scrollable to scroll left/right and see the whole course block.

**Screenshots**
Correct behavior shows on full size screen
correct

Buggy behavior shown on half-sized screen.
wrong

**Additional context**
The page is scrollable to see the right-hand column, but not for the left-hand column

### PR DESCRIPTION
**Pull request by nick-lennox**
**Issue**

closes #338 

**Test Procedure**

Navigate to Explore -> {dept} on mobile/reduced-size window. Displays two columns with each course in the department. Previously the user wouldn't be able to scroll left on this page and not all classes would be visible. 

**Photos**
Before: 

After:

**Additional Info**

I justified the department name centrally, not sure if this was ignored for any particular reason but it seemed to make the UI a bit better in my opinion, but I can change it if need be. For overflow in each courseBox I made it scrollable within that box, but again if we want to change that to something else we definitely can. Admittedly I could've done some more testing, so please give any feedback/issues that you notice.

### CODE REVIEW

**Comment by jshom** [comment]
@nick-lennox can you resolve merge conflicts, blocking temp deploy. thx!

**Comment by 123joshuawu** [comment]
maybe on mobile the courses should be listed in a single column? The title's seem a little cluttered to me

**Comment by nick-lennox** [comment]
> maybe on mobile the courses should be listed in a single column? The titles' seem a little cluttered to me

While I think that'd be fine for most majors, for certain majors that have a ton of courses (CSCI for example) it's a lot of scrolling. I originally implemented it as one column and after talking with @jshom I changed it to two. I still do agree though that the titles are a bit clustered.

File: src/web/src/pages/SubjectExplorer.vue [hunk 1]
```diff
@@ -143,33 +119,34 @@ export default {
...
-      const courses = this.$store.state.courseList;
-      //Obtain All Courses Such That Department Matches The Subject Name.
-      const allTempData = courses.filter((c) => c.department === this.subject);
-      for (let k = 0; k < allTempData.length; k++) {
-        if (k % 2 == 0) leftColumn.push(allTempData[k]);
-        else rightColumn.push(allTempData[k]);
-      }
-      return [leftColumn, rightColumn];
-    },
+
```
Comment (123joshuawu) [inline src/web/src/pages/SubjectExplorer.vue:122]: We probably don't want to change this. These changes were made part of #337. It would probably be best to leave it as is as much as possible

**Review by 123joshuawu — CHANGES_REQUESTED** [review]

**Comment by marchdan** [comment]
@nick-lennox What is the current status of this?

**Review by 123joshuawu — APPROVED** [review]
