### PR TITLE
Fix To Course Information Modal Dark Mode

### LINKED ISSUE #222: UX Bug — Info modal does not respect Dark Mode
**Describe the bug**

The info modal does not respect dark mode

Screen Shot 2020-10-09 at 1 20 36 PM

**To Reproduce**
1. Load any schedule
2. Select dark mode
3. Find a course with (i) extra info
4. Click on (i)

**Expected behavior**
This should be white text on a dark grey background

### PR DESCRIPTION
**Pull request by venkatrsrinivas**
Hello Everyone!
This Is My Pull Request Concerning The Updated Course Information Modal YACS.
Below You Will Find All Important Details:

**Issue**

This Pull Request Should Ideally Closes #222 

**Full Testing Procedure**

*Sample Example(s) To Test Functionality:*
> 1. Run Development Environment w/ Loaded Fall 2020 Semester Data.
> 2. View Course Information Modal For 'Data Structures'. 
> 3. Should Be Visual Presented w/ Correct Background When On Dark Mode. 

**All Relevant Photos**

Original:

Screen Shot 2020-10-20 at 13 35 54

Screen Shot 2020-10-20 at 13 34 50

Final: 

Screen Shot 2020-10-20 at 13 30 46

Screen Shot 2020-10-20 at 13 30 34

NOTE: The Main "Issue" Is That For Dark Mode Styling I Had To Specify The Color B/C var{--dark-primary} Did Not Work Even Though It Had The Same Color Value, ...

### CODE REVIEW

File: src/web/src/pages/CourseScheduler.vue [hunk 1]
```diff
@@ -93,11 +93,15 @@
...
       </b-col>
     </b-row>
+    <!-- NOTE: Content Class Specifies The Styling For Modal In Dark Mode. -->
     <b-modal
       id="courseInfoModal"
       v-if="courseInfoModalCourse"
       v-model="showCourseInfoModal"
       :title="courseInfoModalCourse.name + ' ' + courseInfoModalCourse.title"
+      :content-class="
+        $store.state.darkMode ? 'onStyleDarkMode' : 'offStyleDarkMode'
```
Comment (123joshuawu) [inline src/web/src/pages/CourseScheduler.vue:103]: We only need to have custom css when dark mode is active, so we don't actually need `offStyleDarkMode`. You can "toggle" classes dynamically using the object syntax for class bindings.

**Review by 123joshuawu — CHANGES_REQUESTED** [review]
Looks good, I noticed that the 'x' button in the top right of the card to close the modal is black with faint white outline in darkmode which makes it a little hard to see. Maybe we should change it to a white fill?

File: src/web/src/pages/CourseScheduler.vue [hunk 2]
```diff
@@ -457,6 +460,19 @@ export default {
 };
 </script>
 
+<!-- All Styling For Dark Mode For Course Information Modals.  -->
+<style scoped>
+/deep/ .onStyleDarkMode {
+  background: #22252e;
```
[the remark this answers is not in the document]
Comment (venkatrsrinivas) [reply src/web/src/pages/CourseScheduler.vue:466]: I wanted to do this, but doing that did not work and resulted in White for some Unknown Reason. 
I could not figure out why this was the Case.

[the remark this answers is not in the document]
Comment (123joshuawu) [reply src/web/src/pages/CourseScheduler.vue:466]: Ah, so the modal div is being created as a sibling of the `#root` div which is where the `.dark` class is being applied

[the remark this answers is not in the document]
Comment (123joshuawu) [reply src/web/src/pages/CourseScheduler.vue:466]: Should work now

[the remark this answers is not in the document]
Comment (venkatrsrinivas) [reply src/web/src/pages/CourseScheduler.vue:466]: Hey Josh I just tried it and it did not work ...
Pretty much, all I did was background: 'var{--dark-primary}';

File: src/web/src/pages/CourseScheduler.vue (hunk 1 above)
Comment (venkatrsrinivas) [reply src/web/src/pages/CourseScheduler.vue:103]: What do you mean by toggle classes dynamically? Would I just remove the Else Condition?

**Comment by jshom** [comment]
Looks awesome!!!!!! Once the code tweaks are handled; good for merge 🎊

File: src/web/src/pages/CourseScheduler.vue (hunk 2 above)
[the remark this answers is not in the document]
Comment (123joshuawu) [reply src/web/src/pages/CourseScheduler.vue:466]: You need to use parentheses not brackets: `var(--dark-primary)`

File: src/web/src/pages/CourseScheduler.vue (hunk 1 above)
Comment (123joshuawu) [reply src/web/src/pages/CourseScheduler.vue:103]: You can do class bindings using the object syntax, so like this `:class="{ <class name>: <boolean expr>  }"`

So given `<a :class="{ active: isActive }">` will be rendered as `<a class="active">` when `isActive === true`, and `<a>` when `isActive === false`

File: src/web/src/pages/CourseScheduler.vue (hunk 2 above)
[the remark this answers is not in the document]
Comment (venkatrsrinivas) [reply src/web/src/pages/CourseScheduler.vue:466]: Alright it works. I think also I did not need to use the ' ' because 'var(--dark-primary)' failed, but the other did not. 
Thank you.

File: src/web/src/pages/CourseScheduler.vue (hunk 1 above)
Comment (venkatrsrinivas) [reply src/web/src/pages/CourseScheduler.vue]: Thank you. That makes sense to me.
Just curious if you know where the X is currently being styled? 
I've been trying to look for it.

Comment (123joshuawu) [reply src/web/src/pages/CourseScheduler.vue]: Dont think its being styled, you'll probably need to add a selector to the `dark.scss` file for the X

Comment (venkatrsrinivas) [reply src/web/src/pages/CourseScheduler.vue]: Yes I agree, I didn't manage to find that either.
But is the Code for the X somewhere or is that just implicitly done by the B-Modal?

**Comment by venkatrsrinivas** [comment]
Hello.
I've just updated the X Button.
Here is what it looks like on Dark Mode.
Screen Shot 2020-10-21 at 15 09 11
I've also explicitly set the Color for the X Button on Light Mode as well, so kindly look at the Code/Website and let me know what you think.

File: src/web/src/pages/CourseScheduler.vue [hunk 3]
```diff
@@ -457,6 +462,19 @@ export default {
 };
 </script>
 
+<!-- All Styling For Dark Mode For Course Information Modals.  -->
+<style scoped>
+/deep/ .onStyleDarkMode {
+  background: var(--dark-primary);
+  color: white;
```
Comment (123joshuawu) [inline src/web/src/pages/CourseScheduler.vue:469]: let's use the `dark.scss` variables when we can, so `color: var(--dark-text-primary)` or secondary

File: src/web/src/pages/CourseScheduler.vue [hunk 4]
```diff
@@ -457,6 +462,19 @@ export default {
...
+}
+
+/deep/ .offStyleDarkMode {
```
Comment (123joshuawu) [inline src/web/src/pages/CourseScheduler.vue:472]: no longer need this

**Review by 123joshuawu — APPROVED** [review]
Looks good to me, just a few changes

File: src/web/src/pages/CourseScheduler.vue (hunk 3 above)
Comment (venkatrsrinivas) [reply src/web/src/pages/CourseScheduler.vue:469]: But I thought var(--dark-primary) is the Color described in the Dark.CSS File?

File: src/web/src/pages/CourseScheduler.vue (hunk 4 above)
Comment (venkatrsrinivas) [reply src/web/src/pages/CourseScheduler.vue:472]: Sounds good. I thought I removed it. Will be fixed.

File: src/web/src/pages/CourseScheduler.vue (hunk 3 above)
Comment (123joshuawu) [reply src/web/src/pages/CourseScheduler.vue:469]: Yeah, Im referring to the `color: white`

Comment (venkatrsrinivas) [reply src/web/src/pages/CourseScheduler.vue:469]: Oh alright that makes sense. I'll try that out and see if it works. If not, I'll let you all know.

Comment (venkatrsrinivas) [reply src/web/src/pages/CourseScheduler.vue]: It works I believe. Can you all check it out? I think it's ready for Merge into Master.

File: src/web/src/pages/CourseScheduler.vue (hunk 4 above)
Comment (venkatrsrinivas) [reply src/web/src/pages/CourseScheduler.vue]: Update: This Has Been Removed Through Latest Commit.

**Comment by venkatrsrinivas** [comment]
Update: Still Awaiting One More Approval For Merge.

**Review by 123joshuawu — APPROVED** [review]
