### PR TITLE
User Experience Fix To Department/Major Listing Order 

### LINKED ISSUE #262: UX Bug - Explore Department - Listing Order
**Describe the bug**
The listings appear to order themselves going downwards then wrapping at the end making it difficult to visually group and find classes within a major.

i.e.
```
1 4
2 5
3 6
```

Change this to order since we visually group classes by course level (1xxx, 2xxx, 3xxx, etc.)
```
1 2
3 4
5 6
```

Screen Shot 2020-10-28 at 8 09 37 PM

**Implementation Suggestion**
Use bootstrap row for the entire  with col to chunk the course listings

### PR DESCRIPTION
**Pull request by venkatrsrinivas**
Hello Everyone!
This Is My Pull Request Concerning The Updated Listing Ordering For The Courses In The Department.
NOTE: As Opposed To Dealing W/ Bootstrap + Manually Fixing The Listing Order, It Made More Sense To Simply Change The Data That We Wanted To Display W/I Each Column. 
Below You Will Find All Important Details:

**Issue**

This Pull Request Should Ideally Close #262. 

**Full Testing Procedure**

*Sample Example(s) To Test Functionality:*
> 1. Run Development Environment w/ Loaded Fall 2020 OR Spring 2021 Semester Data.
> 2. Navigate To The Course Explore Page + Click On The CSCI Department. 
> 3. Should Be Visual Presented w/ Correct Ordering Course Displayed, w/ Lower # Courses Populated Towards The Top + Higher # Courses Populated Towards The Bottom. 

**All Relevant Photos**

Original (i.e., Currently In Master Branch):

Screen Shot 2020-10-30 at 13 18 35

Final (i.e., Currently In DepartListingOrder Branch): 

Screen Shot 2020-10-30 at 13 18 57

### CODE REVIEW

File: src/web/src/pages/SubjectExplorer.vue [hunk 1]
```diff
@@ -112,14 +112,15 @@ export default {
...
+    const allTempData = courses.filter(
       (c) => c.department === this.subject
     );
-    this.leftColumnCourses = this.rightColumnCourses.splice(
-      0,
-      Math.ceil(this.rightColumnCourses.length / 2)
-    );
-    this.rightColumnCourses.splice(0, 0);
+
+    for(var k=0; k<allTempData.length-1; k+=2){
```
Comment (123joshuawu) [inline src/web/src/pages/SubjectExplorer.vue:120]: js: `let` for loop iteration variables

**Review by 123joshuawu — APPROVED** [review]

File: src/web/src/pages/SubjectExplorer.vue (hunk 1 above)
Comment (venkatrsrinivas) [reply src/web/src/pages/SubjectExplorer.vue]: My bad, Josh. It should be fixed now.

**Review by IkeLyons — APPROVED** [review]
